Test workflow.

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -7,7 +7,7 @@ on:
   workflow_dispatch:
 
 env:
-  BUILD_VERSION: 'v${{vars.VERSION}}.${{vars.MAJOR}}.${{vars.MINOR}}.${{ github.run_number }}'
+  BUILD_VERSION: v${{ vars.VERSION }}.${{ vars.MAJOR }}.${{ vars.MINOR }}.${{ github.run_number }}
 
 jobs:
   build:
@@ -26,17 +26,22 @@ jobs:
         arduino-cli core install esp32:esp32
 
     - name: Compile firmware
-      with:
-        working_directory: ./src
+      working-directory: ./src
       run: |
         arduino-cli compile \
           --fqbn esp32:esp32:esp32c3 \
           -e \
           --output-dir ../firmware \
+          .
 
     - name: Rename binary for release
       run: |
-        mv ./firmware/esp32.esp32c3/src.ino.bin "./firmware/RDM_RPCC_${{env.BUILD_VERSION}}.bin"
+        if [ ! -f ./firmware/esp32.esp32c3/src.ino.bin ]; then
+          echo "ERROR: Compiled binary not found!"
+          find ./firmware -type f
+          exit 1
+        fi
+        mv ./firmware/esp32.esp32c3/src.ino.bin "./firmware/RDM_RPCC_${{ env.BUILD_VERSION }}.bin"
 
     - name: Create Git tag
       id: tag
@@ -65,6 +70,6 @@ jobs:
       uses: actions/upload-release-asset@v1
       with:
         upload_url: ${{ steps.release.outputs.upload_url }}
-        asset_path: firmware/RDM_RPCC_${{ env.BUILD_VERSION }}.bin
+        asset_path: ./firmware/RDM_RPCC_${{ env.BUILD_VERSION }}.bin
         asset_name: RDM_RPCC_${{ env.BUILD_VERSION }}.bin
         asset_content_type: application/octet-stream
